CREATE TABLE events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  dateTime DATE NOT NULL,
  time TIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  brief VARCHAR(255) NOT NULL,
  imagePath VARCHAR(255)
);