CREATE TABLE volunteers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullName VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(20),
  email VARCHAR(255) NOT NULL,
  volunteerFor VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);